; Minimal php.ini for local dev license server
extension_dir = "C:\\Users\\USER\\AppData\\Local\\Microsoft\\WinGet\\Packages\\PHP.PHP.8.2_Microsoft.Winget.Source_8wekyb3d8bbwe\\ext"
extension=openssl
; reduce noise
display_errors = On
error_reporting = E_ALL
date.timezone = "UTC"
